name: Build and Publish back-end

on:
  # run it on push to the default repository branch
  push:
    branches: [ops/add-git-action]
  # run it during pull request
  pull_request:
    branches: [add-docker]

jobs:
  # define job to build and publish docker image
  build-docker-image:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Git clone repo
        uses: actions/checkout@v1

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: ${{ provider-id }}
          service_account: ${{ service-account }}@${{ project-id }}.iam.gserviceaccount.com
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: us-west2-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build Docker Image
        working-directory: ./
        run: |
          pwd
          ls -l 
          docker build . --file ./apps/main/Dockerfile --tag my-image-name:$(date +%s)

      - name: List of images
        run: docker images 
